### ISSUE TITLE
Get started with wechaty

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/wechat-playground#3]
Using [wechaty/getting-started](https://github.com/wechaty/getting-started) to get started with Wechaty.

**Comment by xuyuji9000** [comment]
When run `npm start` under `./getting-started` .

Meeting the following error message

```
> wechaty-getting-started@1.18.9 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/transpilers/swc.ts:262
      throw new Error(
            ^
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"noInterop":false,"type":"es6","strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"decorators":true,"dynamicImport":true,"importAssertions":true},"target":"es2022","transform":{"decoratorMetadata":true,"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false}},"keepClassNames":true,"experimental":{"keepImportAssertions":true}}}

Caused by:
    unknown field `noInterop`, expected `resolveFully` at line 1 column 433
    at createVariant (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/transpilers/swc.ts:262:13)
    at createSwcOptions (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/transpilers/swc.ts:211:25)
    at create (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/transpilers/swc.ts:56:41)
    at createTranspiler (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/index.ts:784:16)
    at createTranspileOnlyGetOutputFunction (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/index.ts:1341:28)
    at createFromPreloadedConfig (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/index.ts:1411:33)
    at create (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/index.ts:624:10)
    at register (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/index.ts:591:15)
    at Object.registerAndCreateEsmHooks (/Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/src/esm.ts:116:34)
    at file:///Users/yogiman/Workspace/Cache/github/wechaty/getting-started/node_modules/ts-node/esm.mjs:8:7
```

And a monkey patch was suggested.
https://github.com/TypeStrong/ts-node/issues/2070#issuecomment-1738569523

And an already merged PR fix ( https://github.com/TypeStrong/ts-node/pull/2062 ) was mentioned
https://github.com/TypeStrong/ts-node/issues/2070#issue-1910201262

**Comment by xuyuji9000** [comment]
[de5eb64](https://github.com/xuyuji9000/wechat-playground/commit/de5eb64020629fd5e6b3e84a9dbc13741ca1a17e)

Was able to do a simple ding dong feature with wechaty.

Moving this ticket to done.
